name: NYT weekly crawler

on:
  schedule:
    # ── minute hour dom mon dow (UTC) ──
    - cron: '0 9 * * 1'      # every Monday 09:00 UTC
  workflow_dispatch:         # manual “Run workflow” button

jobs:
  fetch-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install deps (no-root)
        run: poetry install --no-interaction --no-root --with dev

      - name: Run one-shot NYT fetch
        env:
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: |
          poetry run python flows/nyt_ingest.py
          ls -l data/raw/nyt | tail -n 5   # sanity peek

      - name: Upload NYT snapshot artefact
        uses: actions/upload-artifact@v4
        with:
          name: nyt-${{ github.run_number }}
          path: data/raw/nyt/*.json
          if-no-files-found: ignore
