name: NYT weekly crawler

on:
  schedule:
    - cron: "0 9 * * 1"   # Mondays 09:00 UTC
  workflow_dispatch: {}

concurrency:
  group: nyt-weekly
  cancel-in-progress: true

jobs:
  fetch-and-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps
        env:
          PREFECT_API_ENABLE: "false"
        run: poetry install --no-interaction --no-root

      - name: Pull last Monday snapshot
        env:
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: poetry run python flows/nyt_ingest.py

      - name: Show latest files
        run: ls -l data/raw/nyt | tail -n 5

      - name: Upload snapshot artefact
        uses: actions/upload-artifact@v4
        with:
          name: nyt-${{ github.run_number }}
          path: data/raw/nyt/*.json
          if-no-files-found: warn
          retention-days: 30
